# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdns_manager', '0006_auto_20151018_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(db_index=True, help_text=b'This field is the actual domain name. This is the field that powerDNS matches when it gets a request. The domainname should be in the format of: domainname.TLD (no trailing dot)', max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='type',
            field=models.CharField(choices=[(b'NATIVE', b'Native'), (b'MASTER', b'Master'), (b'SLAVE', b'Slave')], default=b'MASTER', help_text=b'Select the zone type. Native refers to native SQL replication. Master/Slave refers to DNS server based zone transfers.', max_length=6, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.CharField(help_text=b'This is the actual content of a Resource Record. For instance, in case of an A record, this is the IP address.', max_length=64000, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='record',
            name='ttl',
            field=models.PositiveIntegerField(blank=True, help_text=b'The time in seconds the DNS-clients are allowed to cache this record. Also known as Time To Live (TTL).', null=True, verbose_name='TTL'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[(b'SOA', b'SOA'), (b'NS', b'NS'), (b'A', b'A'), (b'CNAME', b'CNAME')], db_index=True, help_text=b'Select the type of the resource record.', max_length=10, null=True, verbose_name='type'),
        ),
    ]
