# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-15 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('powerdns_manager', '0007_auto_20170309_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('primary_domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='env_as_primary_domain', to='powerdns_manager.Domain')),
                ('secondary_domain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='env_as_secondary_domain', to='powerdns_manager.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'description')),
                ('primary_address', models.CharField(max_length=200)),
                ('primary_address_type', models.IntegerField(choices=[(1, b'A'), (2, b'CNAME')], default=1)),
                ('secondary_address', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_address_type', models.IntegerField(blank=True, choices=[(1, b'A'), (2, b'CNAME')], default=1, null=True)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_ops_inventory.Environment', verbose_name=b'environment')),
            ],
        ),
        migrations.CreateModel(
            name='NodeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSHUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='ssh_specific_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_ops_inventory.SSHUser'),
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dash_ops_inventory.NodeTag'),
        ),
    ]
