# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-15 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_ops_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([('name', 'env')]),
        ),
    ]
