#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          dash-ops-server
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts django (dash-ops) app server
# Description:       starts the django (dash-ops) app server using start-stop-daemon
### END INIT INFO
set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DJANGO_PROJECT=/opt/dash-ops-server
DAEMON=$DJANGO_PROJECT/venv/bin/uwsgi

LOG_DIR=/var/log/dash-ops-server
RUN_DIR=/var/run/dash-ops-server

PIDFILE=$RUN_DIR/uwsgi.pid
INIFILE=$DJANGO_PROJECT/etc/uwsgi/uwsgi.ini

NAME=dash-ops-server
DESC='django of app dash-ops-server and powerdns_manager'
OWNER=pdns-uwsgi
GROUP=pdns-uwsgi

[[ -x $DAEMON ]] || exit 0
[[ -d $RUN_DIR ]] || mkdir $RUN_DIR && chown $OWNER:$GROUP $RUN_DIR
[[ -d $LOG_DIR ]] || mkdir $LOG_DIR && chown $OWNER:$GROUP $LOG_DIR

do_pid_check()
{
    local PIDFILE=$1
    [[ -f $PIDFILE ]] || return 0
    local PID=$(cat $PIDFILE)
    for p in $(pgrep $NAME); do
        [[ $p == $PID ]] && return 1
    done
    return 0
}


do_start()
{
    local START_OPTS=" --ini $INIFILE"
    if do_pid_check $PIDFILE; then
        cd $DJANGO_PROJECT
        $DAEMON $START_OPTS > /dev/null
    else
        echo "Already running!"
    fi
}

send_sig()
{
    set +e
    [[ -f $PIDFILE ]] && kill $1 $(cat $PIDFILE) > /dev/null 2>&1
    set -e
}

wait_and_clean_pidfile()
{
    until do_pid_check $PIDFILE; do
        echo -n "";
    done
    rm -f $PIDFILE
}

do_stop()
{
    send_sig -3
    wait_and_clean_pidfile
}

do_reload()
{
    send_sig -1
}

do_force_reload()
{
    send_sig -15
}

get_status()
{
    send_sig -10
}

case "$1" in
    start)
        echo "Starting $DESC: "
        do_start
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        do_stop
        echo "$NAME."
        ;;
    reload)
        echo -n "Reloading $DESC: "
        do_reload
        echo "$NAME."
        ;;
    force-reload)
        echo -n "Force-reloading $DESC: "
        do_force_reload
        echo "$NAME."
       ;;
    restart)
        echo  "Restarting $DESC: "
        do_stop
        sleep 1
        do_start
        echo "$NAME."
        ;;
    status)
        get_status
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|reload|force-reload|status}">&2
        exit 1
        ;;
esac
exit 0
